### ISSUE TITLE
Comida favorita?

### ISSUE THREAD

**Issue by elin-winter** [pdepjm/2024-tp0-presentacion-Malena8a#1]
Hola Male, qué tal??

Me gustó mucho tu presentación a pesar de que sos team verano (locura total), quería preguntarte nomás cuál era tu comida favorita? Yo tambien soy team salado. Podrías agregarla a tu descripción.

**Comment by Malena8a** [comment]
Hola, todo bien :) 
La verdad me gusta comer de todo, pero si tengo que elegir sin dudas es el pollo a la portuguesa con papas fritas que hace mi abuela.
