### ISSUE TITLE
Género de películas o series preferido?

### ISSUE THREAD

**Issue by npinkas** [pdepjm/2024-tp0-presentacion-Malena8a#2]
Hola! Muy interesante tu presentación! Quería consultarte, que género de series o películas te gusta? Tenés alguna serie o película favorita? Quizás podrías agregarla a tu presentación.

**Comment by Malena8a** [comment]
Holis. No sé si tengo peli favorita, pero los géneros que mas me gustan son dramas y comedias románticas, de las típicas que pasan en la tele los domingos. Y si tengo que decir alguna serie diría que Glee y Avatar son de mis favoritas.
